version: 2
updates:
  # Python dependencies for indexer
  - package-ecosystem: "pip"
    directory: "/indexer"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "python"
      - "indexer"

  # Python dependencies for API
  - package-ecosystem: "pip"
    directory: "/api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "python"
      - "api"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/indexer"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
      - "indexer"

  - package-ecosystem: "docker"
    directory: "/api"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
      - "api"

  - package-ecosystem: "docker"
    directory: "/web"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
      - "web"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"